import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import { renderCprPdf } from '../src/common/zapsign/cpr-pdf';

const output = resolve(process.argv[2] || '/private/tmp/CPR-Financeira-Exemplo-ConectCampo.pdf');

const example = {
  numeroCpr: 'CPR-EXEMPLO-2026-0001',
  purpose: 'EMISSAO',
  type: 'FINANCEIRA',
  status: 'RASCUNHO',
  createdAt: '2026-08-30T12:00:00.000Z',
  emitenteNome: 'Produtora Rural Horizonte Verde Ltda. (FICTÍCIA)',
  emitenteCpfCnpj: '00.000.000/0001-00',
  emitenteEndereco: 'Estrada Municipal Exemplo, km 12, Zona Rural',
  emitenteCidade: 'Sorriso',
  emitenteEstado: 'MT',
  emitenteCarNumero: 'CAR-EXEMPLO-SEM-VALIDADE',
  emitenteEmail: 'emitente.exemplo@conectcampo.invalid',
  emitenteTelefone: '(00) 00000-0000',
  credorNome: 'Fundo Agro Exemplo I (FICTÍCIO)',
  credorCpfCnpj: '11.111.111/0001-11',
  credorTipo: 'Fundo de investimento — exemplo',
  credorEmail: 'credor.exemplo@conectcampo.invalid',
  credorTelefone: '(00) 11111-1111',
  produto: 'Soja em grãos',
  quantidade: 30000,
  unidade: 'sacas de 60 kg',
  safraAno: '2026/2027',
  precoUnitario: 75,
  valorTotal: 2250000,
  valorFace: 2500000,
  localEntrega: 'Armazém Exemplo, Sorriso/MT',
  dataEntrega: '2027-04-30T00:00:00.000Z',
  dataVencimento: '2028-07-31T00:00:00.000Z',
  prazoMeses: 24,
  carenciaMeses: 6,
  garantiaTipo: 'Penhor rural de primeiro grau e aval',
  garantiaDescricao: 'Safra de soja 2026/2027 produzida na Fazenda Horizonte Verde, além de aval pessoal do garantidor cadastrado.',
  garantiaValor: 4000000,
  finalidade: 'Custeio agrícola e aquisição de insumos da safra 2026/2027',
  valorCaptacao: 2350000,
  conectcampoFeeRate: 0.06,
  conectcampoFeeValue: null,
  custoEmissao: 20000,
  signatureStatus: 'NAO_INICIADA',
  observacoes: 'Todos os nomes, documentos, endereços e valores deste arquivo são fictícios e servem exclusivamente para demonstrar o novo padrão documental da ConectCampo.',
  contractData: {
    minutaExemplo: true,
    localEmissao: 'Sorriso/MT',
    dataEmissao: '2026-08-30T00:00:00.000Z',
    emitenteQualificacao: 'Sociedade empresária rural fictícia, representada na forma de seu contrato social',
    emitenteCep: '00000-000',
    emitenteRepresentante: 'João Produtor Exemplo — administrador fictício',
    emitenteBanco: 'Banco Exemplo',
    emitenteAgencia: '0001',
    emitenteConta: '000000-0',
    credorQualificacao: 'Veículo de investimento fictício, representado por sua administradora',
    credorEndereco: 'Avenida Financeira Exemplo, 1000',
    credorCidade: 'São Paulo',
    credorEstado: 'SP',
    credorCep: '11111-111',
    credorRepresentante: 'Representante Legal Exemplo',
    avalistas: [{
      nome: 'Maria Garantidora Exemplo (FICTÍCIA)',
      cpfCnpj: '000.000.000-00',
      qualificacao: 'Produtora rural fictícia',
      endereco: 'Estrada Municipal Exemplo, km 12, Zona Rural, Sorriso/MT',
      email: 'avalista.exemplo@conectcampo.invalid',
      telefone: '(00) 22222-2222',
    }],
    produtoQualidade: 'Tipo 1, umidade máxima de 14%, impurezas conforme padrão contratual',
    produtoPadrao: 'Soja em grãos, padrão comercial de exportação — exemplo',
    propriedadeNome: 'Fazenda Horizonte Verde (FICTÍCIA)',
    propriedadeEndereco: 'Zona Rural de Sorriso/MT — coordenadas omitidas por se tratar de exemplo',
    propriedadeMatricula: 'MATRÍCULA-EXEMPLO-0001',
    indicePreco: 'Indicador público a confirmar na contratação',
    fontePreco: 'Fonte independente indicada no contrato definitivo',
    mercadoReferencia: 'Praça de Sorriso/MT',
    taxaJurosMensal: 0.95,
    taxaJurosAnual: 12.01,
    cetMensal: 1.08,
    cetAnual: 13.77,
    multaMoraPct: 2,
    jurosMoraMensalPct: 1,
    encargosAdicionais: 'Atualização pelo índice contratual e despesas de cobrança efetivamente comprovadas',
    valorCredito: 2500000,
    valorIof: 35000,
    valorLiquido: 2445000,
    formaLiquidacao: 'Transferência bancária em moeda corrente nacional',
    localPagamento: 'Conta bancária indicada pelo CREDOR no instrumento definitivo',
    cronograma: [
      { numero: 1, vencimento: '2027-01-31', principal: 500000, encargos: 45000, total: 545000 },
      { numero: 2, vencimento: '2027-07-31', principal: 625000, encargos: 42000, total: 667000 },
      { numero: 3, vencimento: '2028-01-31', principal: 625000, encargos: 38000, total: 663000 },
      { numero: 4, vencimento: '2028-07-31', principal: 750000, encargos: 30000, total: 780000 },
    ],
    garantiaProprietario: 'Produtora Rural Horizonte Verde Ltda. (FICTÍCIA)',
    garantiaRegistro: 'Livro e protocolo a preencher após formalização',
    garantiaGrau: 'Primeiro grau — exemplo',
    registradora: 'Entidade autorizada a definir na emissão definitiva',
    numeroRegistro: 'PENDENTE',
    foroCidade: 'Sorriso',
    foroEstado: 'MT',
    contatoNotificacoes: 'emitente.exemplo@conectcampo.invalid · credor.exemplo@conectcampo.invalid',
  },
};

renderCprPdf(example)
  .then((buffer) => writeFile(output, buffer))
  .then(() => process.stdout.write(`${output}\n`))
  .catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
    process.exitCode = 1;
  });
