import Foundation

struct RuralDay: Codable { let date: String; let count: Int }
struct RuralLocation: Codable { let latitude: Double; let longitude: Double; let label: String }
struct RuralWidgetSnapshot: Codable {
    let agendaEnabled: Bool
    let location: RuralLocation?
    let days: [RuralDay]
    let updatedAt: Double
    // Generated by the native bridge, never an account identifier or credential.
    var revision: String? = nil
}

enum RuralWidgetStore {
    static let group = "group.digital.conectcampo.app.widgets"
    static var file: URL? { FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: group)?.appendingPathComponent("rural-widgets-v1.json") }
    static func read() -> RuralWidgetSnapshot? {
        guard let url = file, let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(RuralWidgetSnapshot.self, from: data)
    }
    static func write(_ snapshot: RuralWidgetSnapshot) throws {
        guard var url = file else { throw CocoaError(.fileNoSuchFile) }
        let data = try JSONEncoder().encode(snapshot)
        try data.write(to: url, options: [.atomic, .completeFileProtectionUntilFirstUserAuthentication])
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        try url.setResourceValues(values)
    }
    static func clear() throws {
        guard let url = file, FileManager.default.fileExists(atPath: url.path) else { return }
        try FileManager.default.removeItem(at: url)
    }
}
